name: demo
on: workflow_dispatch
jobs: 
     build:
          runs-on: ubuntu-latest
          steps:
           - name: message
             run: echo "Welcome - GitHub Actions learning"
           - name: list
             run: ls -lart
           - name: host name
             run: hostname
           - name: history
             run: history

         
