name: demo
on: push
jobs: 
     build:
          runs-on: ubuntu-latest
          steps:
           - name: message
             run: echo "Welcome - GitHub Actions learning"
           - name: list
             run: ls -lart
           - name: host name
             run: hostname
           - name: process
             run: top

         
