name: Git Repo creation

on:
  workflow_dispatch:
env:
  ORG_TOKEN: ${{ secrets.ORG_TOKEN }}
  #SOME_SECRET: some-secret-value
jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Creating Organization Repository
    steps:
      - uses: actions/checkout@v3
      - uses: howlowck/create-repo@v1.0
        with:
          zipPath: './src.zip'
          repoOrg: 'howlowck'
          repoName: 'my-new-app'
          repoDescription: 'My Shiny New Repo'
          repoVisibility: 'public'
          securityToken: ${{ secrets.ORG_TOKEN }}
          envsToRepoSecrets: ORG_TOKEN,SOME_SECRET  
